// Jeu d'emojis curé pour le picker des « assets secteur » — recherche par
// mots-clés (FR/EN). Couvre métiers/secteurs + emojis génériques utiles.
export type EmojiEntry = { char: string; keywords: string };

export const EMOJIS: EmojiEntry[] = [
  // Métiers & secteurs
  { char: "⚖️", keywords: "avocat justice droit juridique balance loi tribunal" },
  { char: "🏛️", keywords: "tribunal institution banque batiment colonnes administration" },
  { char: "⛵", keywords: "voilier nautisme bateau mer voile navigation" },
  { char: "🚤", keywords: "bateau nautisme vitesse mer hors-bord" },
  { char: "⚓", keywords: "ancre nautisme marine mer port" },
  { char: "🍷", keywords: "vin viticole verre rouge domaine oenologie" },
  { char: "🍇", keywords: "raisin viticole vigne vendange fruit" },
  { char: "🍾", keywords: "champagne fete bouteille celebration vin" },
  { char: "🚀", keywords: "fusee startup croissance lancement rocket boost" },
  { char: "🛍️", keywords: "shopping ecommerce sac boutique achat vente" },
  { char: "🛒", keywords: "panier ecommerce courses achat caddie" },
  { char: "🏪", keywords: "magasin boutique commerce store" },
  { char: "💳", keywords: "carte paiement bancaire achat ecommerce" },
  { char: "🍽️", keywords: "restaurant assiette couverts cuisine gastronomie" },
  { char: "👨‍🍳", keywords: "chef cuisinier restaurant cuisine" },
  { char: "🍔", keywords: "burger fast food restaurant repas" },
  { char: "☕", keywords: "cafe boisson coffee bar" },
  { char: "🏠", keywords: "maison immobilier home logement" },
  { char: "🏢", keywords: "immeuble bureau entreprise batiment immobilier" },
  { char: "🏗️", keywords: "btp construction chantier grue batiment" },
  { char: "👷", keywords: "btp ouvrier chantier construction casque" },
  { char: "🔨", keywords: "marteau btp bricolage outil construction" },
  { char: "🩺", keywords: "sante medical stethoscope docteur medecin" },
  { char: "💊", keywords: "sante pharmacie medicament pilule" },
  { char: "🦷", keywords: "dentiste dent sante soin" },
  { char: "💇", keywords: "coiffure beaute salon cheveux" },
  { char: "💅", keywords: "ongles beaute manucure soin" },
  { char: "💄", keywords: "maquillage beaute cosmetique rouge levres" },
  { char: "✈️", keywords: "avion voyage tourisme vol vacances" },
  { char: "🏖️", keywords: "plage tourisme vacances mer soleil" },
  { char: "🗺️", keywords: "carte voyage tourisme map itineraire" },
  { char: "🏋️", keywords: "sport fitness salle musculation gym" },
  { char: "⚽", keywords: "football sport ballon foot" },
  { char: "🎓", keywords: "formation education diplome ecole etudiant" },
  { char: "📚", keywords: "livres formation education lecture apprentissage" },
  { char: "🎨", keywords: "art creatif design peinture couleur" },
  { char: "📷", keywords: "photo photographie appareil camera" },
  { char: "🎬", keywords: "video film cinema production tournage" },
  { char: "🎵", keywords: "musique son audio note" },
  { char: "🌱", keywords: "ecologie nature plante green croissance bio" },
  { char: "🌿", keywords: "nature plante feuille bio ecologie herbe" },
  { char: "🐾", keywords: "animaux pattes veterinaire animalerie" },
  { char: "🚗", keywords: "voiture auto automobile garage transport" },
  { char: "🔧", keywords: "outil mecanique reparation garage cle" },

  // Tech & business
  { char: "💻", keywords: "ordinateur laptop web site informatique tech" },
  { char: "🖥️", keywords: "ecran ordinateur bureau desktop web" },
  { char: "📱", keywords: "telephone mobile smartphone app application" },
  { char: "🌐", keywords: "web internet monde globe site online" },
  { char: "📈", keywords: "croissance graphique hausse stats performance" },
  { char: "📊", keywords: "graphique stats donnees analyse dashboard" },
  { char: "💼", keywords: "business entreprise mallette travail pro" },
  { char: "💡", keywords: "idee ampoule innovation creativite lumiere" },
  { char: "🎯", keywords: "cible objectif but target precision" },
  { char: "🏆", keywords: "trophee gagnant succes prix champion" },
  { char: "🥇", keywords: "medaille premier or gagnant podium" },
  { char: "⭐", keywords: "etoile star favori note qualite" },
  { char: "✨", keywords: "etincelles brillant magie nouveau eclat" },
  { char: "🔥", keywords: "feu tendance hot populaire flamme" },
  { char: "💎", keywords: "diamant premium luxe qualite gemme" },
  { char: "👑", keywords: "couronne roi luxe premium leader" },
  { char: "🚩", keywords: "drapeau objectif etape marqueur" },
  { char: "📌", keywords: "epingle punaise localisation important" },
  { char: "📍", keywords: "localisation position lieu carte pin" },
  { char: "🔑", keywords: "cle acces securite solution" },
  { char: "🔒", keywords: "cadenas securite protection ferme" },
  { char: "✅", keywords: "validation coche ok fait reussi check" },
  { char: "✔️", keywords: "coche valide ok check oui" },
  { char: "➡️", keywords: "fleche droite suivant direction" },
  { char: "⚡", keywords: "eclair rapide energie vitesse boost" },
  { char: "🛠️", keywords: "outils reparation bricolage maintenance" },
  { char: "⚙️", keywords: "engrenage reglage parametre mecanique config" },
  { char: "📦", keywords: "colis boite livraison expedition logistique" },
  { char: "🚚", keywords: "camion livraison transport logistique" },
  { char: "📣", keywords: "megaphone annonce communication marketing pub" },
  { char: "📢", keywords: "haut-parleur annonce communication marketing" },
  { char: "💬", keywords: "bulle message chat discussion communication" },
  { char: "❤️", keywords: "coeur amour like rouge favori" },
  { char: "🤝", keywords: "poignee main accord partenariat deal collaboration" },
  { char: "👍", keywords: "pouce like bien ok approbation" },
  { char: "🙌", keywords: "mains bravo celebration succes" },
  { char: "👏", keywords: "applaudissements bravo felicitations" },
  { char: "🎉", keywords: "fete celebration party confettis lancement" },
  { char: "🎁", keywords: "cadeau offre promo present" },

  // Nature & divers
  { char: "☀️", keywords: "soleil beau temps jour ete lumiere" },
  { char: "🌙", keywords: "lune nuit soir dark" },
  { char: "🌊", keywords: "vague mer ocean eau flow" },
  { char: "🌍", keywords: "terre monde globe planete international" },
  { char: "🌳", keywords: "arbre nature foret bois ecologie" },
  { char: "🌸", keywords: "fleur printemps rose beaute nature" },
  { char: "❄️", keywords: "neige hiver froid flocon" },
  { char: "🐶", keywords: "chien animal compagnie veterinaire" },
  { char: "🐱", keywords: "chat animal compagnie veterinaire" },
  { char: "🦋", keywords: "papillon transformation nature leger" },
  { char: "🔔", keywords: "cloche notification alerte rappel" },
  { char: "📅", keywords: "calendrier date rendez-vous planning agenda" },
  { char: "⏰", keywords: "reveil horloge temps heure rapide" },
  { char: "📞", keywords: "telephone appel contact phone" },
  { char: "✉️", keywords: "email courrier message contact enveloppe" },
  { char: "📝", keywords: "note ecrire memo redaction crayon" },
  { char: "🖊️", keywords: "stylo ecrire signature redaction" },
  { char: "🔍", keywords: "loupe recherche seo zoom trouver" },
  { char: "💰", keywords: "argent sac money finance budget" },
  { char: "💵", keywords: "billet argent money cash dollar" },
  { char: "🏷️", keywords: "etiquette prix tag promo solde" },
  { char: "🧭", keywords: "boussole direction navigation guide" },
  { char: "🗂️", keywords: "dossier classement fichiers organisation" },
  { char: "📁", keywords: "dossier fichier classement document" },
  { char: "🔗", keywords: "lien chaine url maillage connexion" },
  { char: "🧩", keywords: "puzzle piece solution integration" },
  { char: "🛡️", keywords: "bouclier protection securite garantie defense" },
];
